image: docker:18.06

services:
 - docker:dind

stages:
 - build
 - deploy

before_script:
 - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE/$COMPONENT
  IMAGE_COMMIT_TAG: $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_SHA
  IMAGE_BRANCH_TAG: $CI_REGISTRY_IMAGE/$COMPONENT:$CI_COMMIT_REF_SLUG

build_api:
  stage: build
  variables:
    COMPONENT: api
  script:
    - docker build -t $IMAGE_COMMIT_TAG api/
    - docker run $IMAGE_COMMIT_TAG python -m pytest

    - docker tag $IMAGE_COMMIT_TAG $IMAGE_BRANCH_TAG
    - docker push $IMAGE_NAME

build_web:
  stage: build
  variables:
    COMPONENT: web
  script:
    - docker build -t web/dev --target dev web/
    - docker run -e CI web/dev npm test
    
    - docker build -t $IMAGE_COMMIT_TAG web/

    - docker tag $IMAGE_COMMIT_TAG $IMAGE_BRANCH_TAG
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  script:
    - k8s/bin/deploy.sh
  environment:
    name: production
    url: https://askme.cereda.me
  only:
  - master
