version: '3.4'

services:
  api:
    build: ./api
    depends_on:
     - db
    ports:
     - "5000:5000"
    environment:
     - FLASK_APP=api.py
     - DATABASE_URL=postgresql://postgres:secret@db/postgres
    volumes:
     - ./api:/app:rw

  db:
    image: "postgres:10"
    environment:
     - POSTGRES_PASSWORD=secret

  db-admin:
    image: "dpage/pgadmin4"
    depends_on:
     - db
    ports:
     - "127.0.0.1:5005:80"
    environment:
     - PGADMIN_DEFAULT_EMAIL=admin
     - PGADMIN_DEFAULT_PASSWORD=admin

  web:
    build:
      context: ./web
      target: dev
    depends_on:
     - api
    ports:
     - "3000:3000"
    environment:
     - CHOKIDAR_USEPOLLING=1
    volumes:
     - ./web/public:/app/public:rw
     - ./web/src:/app/src:rw
