apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage-claim
  labels:
    pruneTag: askme
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
